### ISSUE TITLE
Failed to load the local-server-express package

### ISSUE THREAD

**Issue by campriest** [nakajmg/local-server-express#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [local-server-express](https://github.com/nakajmg/local-server-express) package, v0.2.2
### Stack Trace

Failed to load the local-server-express package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Users/cameronpriestley/Desktop/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/cameronpriestley/.atom/packages/local-server-express/lib/local-server-express-view.coffee:6:10)
    at Object.<anonymous> (/Users/cameronpriestley/.atom/packages/local-server-express/lib/local-server-express-view.coffee:84:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Users/cameronpriestley/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
local-server-express, v0.2.2

# Dev
No dev packages
```

**Comment by nakajmg** [comment]
Fixed this issue then release [v0.3.0](https://github.com/nakajmg/local-server-express/releases/tag/v0.3.0)

Thanks for reporting. Plz try update package :arrow_heading_up:
