### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by rodzurek** [nakajmg/local-server-express#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [local-server-express](https://github.com/nakajmg/local-server-express) package, v0.3.1
### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At C:\Users\USUARIO\.atom\packages\local-server-express\lib\local-server-express.coffee:44

TypeError: Cannot read property 'file' of undefined
  at Object.module.exports.getPaths (C:\Users\USUARIO\.atom\packages\local-server-express\lib\local-server-express.coffee:44:26)
  at Object.module.exports.run (C:\Users\USUARIO\.atom\packages\local-server-express\lib\local-server-express.coffee:25:32)
  at C:\Users\USUARIO\.atom\packages\local-server-express\lib\local-server-express.coffee:14:8
  at Server.onListen (C:\Users\USUARIO\.atom\packages\local-server-express\node_modules\portfinder\lib\portfinder.js:48:5)
  at Server.g (events.js:257:16)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:163:7)
  at net.js:1192:12
  at process._tickCallback (node.js:357:13)

```
### Commands

```
     -6:37.4.0 development-server:toggle (atom-text-editor.editor.is-focused)
  2x -6:27.9.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-ui.theme-atom-dark-syntax)
  2x -5:46.8.0 core:cancel (div.settings-view.pane-item)
     -5:36.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:36 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -4:56.5.0 local-server-express:run (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-ui.theme-atom-dark-syntax)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "railscasts-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
linter, v1.1.0
local-server-express, v0.3.1
minimap, v4.10.1

# Dev
No dev packages
```

**Comment by doot0** [comment]
I get this on OSX too.
